name: Build & Deploy

on:
  push:
    branches: [ staging ]

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current code
      uses: actions/checkout@v2

    - name: Install packages
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Set Git identity
      run: git config --global user.name "GitHub Actions"

    - name: Build and deploy site
      run: npm run deploy:ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    